name: "\U0001F41E Report a problem"
description: "Report an issue"
title: "Bug: (fill in)"
labels:
  - bug
  - "repro:needed"
body:
- type: textarea
  attributes:
    label: Environment
    description: |
      Please tell us about how you're running the plugin
    value: |
        Node version: 
        npm version: 
        Backstage version: 
        Plugin version: 
        Operating System: 
  validations:
    required: true
- type: textarea
  attributes:
    label: What did you do?
    description: |
      Please include a *minimal* reproduction case. If possible, include a link to a reproduction of the problem. Otherwise, include source code, configuration file(s), and any other information about how you're using the plugin. You can use Markdown in this field.
    value: |
      <details>
      <summary>Configuration</summary>

      ```
      <!-- Paste your configuration here -->
      ```
      </details>

      ```js
      <!-- Paste your code here -->
      ```
  validations:
    required: true
- type: textarea
  attributes:
    label: What did you expect to happen?
    description: |
      You can use Markdown in this field.
  validations:
    required: true
- type: textarea
  attributes:
    label: What actually happened?
    description: |
      You can use Markdown in this field.
  validations:
    required: true
- type: input
  attributes:
    label: Link to Minimal Reproducible Example
    description: 'Link to a [StackBlitz](https://stackblitz.com) or GitHub repo with a minimal reproduction of the problem. **A minimal reproduction is required** so that others can help debug your issue. If a report is vague (e.g. just a generic error message) and has no reproduction, it may be auto-closed.'
    placeholder: 'https://stackblitz.com/abcd1234'
  validations:
    required: true
- type: checkboxes
  attributes:
    label: Participation
    options:
      - label: I am willing to submit a pull request for this issue.
        required: false
- type: textarea
  attributes:
    label: Additional comments
    description: Is there anything else that's important for the team to know?
