name: "\U0001F4DD Request a change"
description: "Request a change that is not a bug fix"
title: "Change Request: (fill in)"
labels:
  - enhancement
  - core
body:
- type: input
  attributes:
    label: Plugin version
    description: |
      What version of the plugin are you currently using?
    placeholder: |
      e.g. v1.0.0
  validations:
    required: true
- type: textarea
  attributes:
    label: What problem do you want to solve?
    description: |
      Please explain your use case in as much detail as possible.
    placeholder: |
      Currently...
  validations:
    required: true
- type: textarea
  attributes:
    label: What do you think is the correct solution?
    description: |
      Please explain how you'd like to change the plugin to address the problem.
    placeholder: |
      I'd like it to...
  validations:
    required: true
- type: checkboxes
  attributes:
    label: Participation
    options:
      - label: I am willing to submit a pull request for this change.
        required: false
- type: textarea
  attributes:
    label: Additional comments
    description: Is there anything else that's important for the team to know?
